# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\CopyGUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(572, 405)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/copy2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 4, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.tab_1)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_4.addWidget(self.line_4, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_1)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 2, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.tab_1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dest_path_comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.dest_path_comboBox.setEditable(True)
        self.dest_path_comboBox.setObjectName("dest_path_comboBox")
        self.verticalLayout_2.addWidget(self.dest_path_comboBox)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.dest_files_table = QtWidgets.QTableWidget(self.groupBox_2)
        self.dest_files_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.dest_files_table.setDragEnabled(True)
        self.dest_files_table.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.dest_files_table.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.dest_files_table.setAlternatingRowColors(True)
        self.dest_files_table.setGridStyle(QtCore.Qt.NoPen)
        self.dest_files_table.setObjectName("dest_files_table")
        self.dest_files_table.setColumnCount(0)
        self.dest_files_table.setRowCount(0)
        self.dest_files_table.horizontalHeader().setVisible(False)
        self.dest_files_table.horizontalHeader().setStretchLastSection(True)
        self.dest_files_table.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.dest_files_table)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 2, 7, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 6, 1, 1, 1)
        self.copy_selected_btn = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copy_selected_btn.sizePolicy().hasHeightForWidth())
        self.copy_selected_btn.setSizePolicy(sizePolicy)
        self.copy_selected_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.copy_selected_btn.setObjectName("copy_selected_btn")
        self.gridLayout_2.addWidget(self.copy_selected_btn, 5, 1, 1, 1)
        self.edit_paths_btn = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_paths_btn.sizePolicy().hasHeightForWidth())
        self.edit_paths_btn.setSizePolicy(sizePolicy)
        self.edit_paths_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.edit_paths_btn.setObjectName("edit_paths_btn")
        self.gridLayout_2.addWidget(self.edit_paths_btn, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 3, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.src_path_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.src_path_comboBox.setEditable(True)
        self.src_path_comboBox.setDuplicatesEnabled(False)
        self.src_path_comboBox.setFrame(True)
        self.src_path_comboBox.setObjectName("src_path_comboBox")
        self.verticalLayout.addWidget(self.src_path_comboBox)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.src_files_table = QtWidgets.QTableWidget(self.groupBox)
        self.src_files_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.src_files_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.src_files_table.setDragEnabled(True)
        self.src_files_table.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.src_files_table.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.src_files_table.setAlternatingRowColors(True)
        self.src_files_table.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.src_files_table.setGridStyle(QtCore.Qt.NoPen)
        self.src_files_table.setObjectName("src_files_table")
        self.src_files_table.setColumnCount(0)
        self.src_files_table.setRowCount(0)
        self.src_files_table.horizontalHeader().setVisible(False)
        self.src_files_table.horizontalHeader().setStretchLastSection(True)
        self.src_files_table.verticalHeader().setVisible(False)
        self.src_files_table.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.src_files_table)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 7, 1)
        self.copy_all_btn = QtWidgets.QPushButton(self.tab_2)
        self.copy_all_btn.setObjectName("copy_all_btn")
        self.gridLayout_2.addWidget(self.copy_all_btn, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem5, 0, 1, 1, 1)
        self.delete_selected_btn = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_selected_btn.sizePolicy().hasHeightForWidth())
        self.delete_selected_btn.setSizePolicy(sizePolicy)
        self.delete_selected_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.delete_selected_btn.setObjectName("delete_selected_btn")
        self.gridLayout.addWidget(self.delete_selected_btn, 2, 1, 1, 1)
        self.delete_all_btn = QtWidgets.QPushButton(self.tab_3)
        self.delete_all_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.delete_all_btn.setObjectName("delete_all_btn")
        self.gridLayout.addWidget(self.delete_all_btn, 3, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.src_paths_table = QtWidgets.QTableWidget(self.groupBox_4)
        self.src_paths_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.src_paths_table.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.src_paths_table.setDragEnabled(False)
        self.src_paths_table.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.src_paths_table.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.src_paths_table.setAlternatingRowColors(True)
        self.src_paths_table.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.src_paths_table.setGridStyle(QtCore.Qt.NoPen)
        self.src_paths_table.setObjectName("src_paths_table")
        self.src_paths_table.setColumnCount(0)
        self.src_paths_table.setRowCount(0)
        self.src_paths_table.horizontalHeader().setVisible(False)
        self.src_paths_table.horizontalHeader().setStretchLastSection(True)
        self.src_paths_table.verticalHeader().setVisible(False)
        self.src_paths_table.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.src_paths_table)
        self.gridLayout.addWidget(self.groupBox_4, 0, 0, 7, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dest_paths_table = QtWidgets.QTableWidget(self.groupBox_3)
        self.dest_paths_table.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.dest_paths_table.setDragEnabled(False)
        self.dest_paths_table.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.dest_paths_table.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.dest_paths_table.setAlternatingRowColors(True)
        self.dest_paths_table.setGridStyle(QtCore.Qt.NoPen)
        self.dest_paths_table.setObjectName("dest_paths_table")
        self.dest_paths_table.setColumnCount(0)
        self.dest_paths_table.setRowCount(0)
        self.dest_paths_table.horizontalHeader().setVisible(False)
        self.dest_paths_table.horizontalHeader().setStretchLastSection(True)
        self.dest_paths_table.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.dest_paths_table)
        self.gridLayout.addWidget(self.groupBox_3, 0, 2, 7, 1)
        self.back_btn = QtWidgets.QPushButton(self.tab_3)
        self.back_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.back_btn.setObjectName("back_btn")
        self.gridLayout.addWidget(self.back_btn, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout.addItem(spacerItem6, 4, 1, 3, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 572, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "COPY RIGHT : NIC Corporation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Page"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Destination"))
        self.dest_files_table.setSortingEnabled(False)
        self.copy_selected_btn.setText(_translate("MainWindow", "Copy selected"))
        self.edit_paths_btn.setText(_translate("MainWindow", "Edit_paths"))
        self.groupBox.setTitle(_translate("MainWindow", "Source"))
        self.src_files_table.setSortingEnabled(False)
        self.copy_all_btn.setText(_translate("MainWindow", "Copy all"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Copy"))
        self.delete_selected_btn.setText(_translate("MainWindow", "Delete Selected"))
        self.delete_all_btn.setText(_translate("MainWindow", "Delete ALL"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Source"))
        self.src_paths_table.setSortingEnabled(False)
        self.groupBox_3.setTitle(_translate("MainWindow", "Destination"))
        self.dest_paths_table.setSortingEnabled(False)
        self.back_btn.setText(_translate("MainWindow", "Back"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Edit_paths"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
